filter:
    excluded_paths:
        - app/autoload.php
        - app/bootstrap.php.cache
        - app/check.php
        - app/Resources/public/bin/*
        - app/SymfonyRequirements.php
        - app/Tests/*
        - bin/*
        - vendor/*
        - web/config.php

tools:
    # Similar code detector
    php_sim: true

    # Metrics
    php_pdepend: true

    # Some metrics + bug detection/auto-fixes
    php_analyzer: true

    php_changetracking: true

    # Test coverage
    #php_code_coverage: true

    php_mess_detector: true

    sensiolabs_security_checker: true
