filter:
    excluded_paths:
        - vendor/*
        - app/*
        - bin/*
        - src/App/Resources/public/bin/*
        - web/config.php

tools:
    # Similar code detector
    php_sim: true

    # Metrics
    php_pdepend: true

    # Some metrics + bug detection/auto-fixes
    php_analyzer: true

    # Test coverage
    php_code_coverage: true

    php_mess_detector: true

    sensiolabs_security_checker: true
