imports:
    - { resource: parameters.yml }
#    - { resource: security.yml }

framework:
    esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_base_urls: %assets_base_urls%
        #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true
        name:           _CHITANKA

services:
    twig.extension.chitanka:
        class: Chitanka\LibBundle\Twig\Extension
        tags:
            - { name: twig.extension }

#     kernel.listener.chitanka:
#         class: Chitanka\LibBundle\Listener\Listener
#         tags:
#             - { name: kernel.listener, event: core.security, method: run }

    doctrine.listener:
        class: Chitanka\LibBundle\Listener\DoctrineListener
        tags:
            - { name: doctrine.dbal.default_event_listener }
            #- { name: doctrine.common.event_listener }

    feedback_form:
        class: Chitanka\LibBundle\Form\Type\FeedbackType
        tags:
           -  { name: form.type }

    text_rating_form:
        class: Chitanka\LibBundle\Form\Type\TextRatingType
        tags:
           -  { name: form.type }

    text_label_form:
        class: Chitanka\LibBundle\Form\Type\TextLabelType
        tags:
           -  { name: form.type }

    label_form:
        class: Chitanka\LibBundle\Form\Type\LabelType
        tags:
           -  { name: form.type }

    chitanka.admin.person:
        class: Chitanka\LibBundle\Admin\PersonAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_main, label: admin.person }
        arguments: [null, Chitanka\LibBundle\Entity\Person, LibBundle:PersonAdmin]
    chitanka.admin.book:
        class: Chitanka\LibBundle\Admin\BookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_main, label: admin.book }
        arguments: [null, Chitanka\LibBundle\Entity\Book, LibBundle:BookAdmin]
    chitanka.admin.text:
        class: Chitanka\LibBundle\Admin\TextAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_main, label: admin.text }
        arguments: [null, Chitanka\LibBundle\Entity\Text, LibBundle:TextAdmin]
    chitanka.admin.series:
        class: Chitanka\LibBundle\Admin\SeriesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_main, label: admin.series }
        arguments: [null, Chitanka\LibBundle\Entity\Series, LibBundle:SeriesAdmin]
    chitanka.admin.label:
        class: Chitanka\LibBundle\Admin\LabelAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_main, label: admin.label }
        arguments: [null, Chitanka\LibBundle\Entity\Label, LibBundle:LabelAdmin]
    chitanka.admin.category:
        class: Chitanka\LibBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_main, label: admin.category }
        arguments: [null, Chitanka\LibBundle\Entity\Category, LibBundle:CategoryAdmin]
    chitanka.admin.sequence:
        class: Chitanka\LibBundle\Admin\SequenceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_main, label: admin.sequence }
        arguments: [null, Chitanka\LibBundle\Entity\Sequence, LibBundle:SequenceAdmin]
    chitanka.admin.text_comment:
        class: Chitanka\LibBundle\Admin\TextCommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_main, label: admin.text_comment }
        arguments: [null, Chitanka\LibBundle\Entity\TextComment, LibBundle:TextCommentAdmin]

    chitanka.admin.wanted_book:
        class: Chitanka\LibBundle\Admin\WantedBookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_secondary, label: admin.wantedbook }
        arguments: [null, Chitanka\LibBundle\Entity\WantedBook, LibBundle:WantedBookAdmin]
    chitanka.admin.featured_book:
        class: Chitanka\LibBundle\Admin\FeaturedBookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_secondary, label: admin.featuredbook }
        arguments: [null, Chitanka\LibBundle\Entity\FeaturedBook, LibBundle:FeaturedBookAdmin]
    chitanka.admin.foreign_book:
        class: Chitanka\LibBundle\Admin\ForeignBookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_secondary, label: admin.foreignbook }
        arguments: [null, Chitanka\LibBundle\Entity\ForeignBook, LibBundle:ForeignBookAdmin]
    chitanka.admin.site:
        class: Chitanka\LibBundle\Admin\SiteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_secondary, label: admin.site }
        arguments: [null, Chitanka\LibBundle\Entity\Site, LibBundle:SiteAdmin]
    chitanka.admin.book_site:
        class: Chitanka\LibBundle\Admin\BookSiteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_secondary, label: admin.booksite }
        arguments: [null, Chitanka\LibBundle\Entity\BookSite, LibBundle:BookSiteAdmin]
    chitanka.admin.wiki_site:
        class: Chitanka\LibBundle\Admin\WikiSiteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_secondary, label: admin.wikisite }
        arguments: [null, Chitanka\LibBundle\Entity\WikiSite, LibBundle:WikiSiteAdmin]
    chitanka.admin.question:
        class: Chitanka\LibBundle\Admin\QuestionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_secondary, label: admin.question }
        arguments: [null, Chitanka\LibBundle\Entity\Question, LibBundle:QuestionAdmin]
    chitanka.admin.license:
        class: Chitanka\LibBundle\Admin\LicenseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_secondary, label: admin.license }
        arguments: [null, Chitanka\LibBundle\Entity\License, LibBundle:LicenseAdmin]

    chitanka.admin.book_link:
        class: Chitanka\LibBundle\Admin\BookLinkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_links, label: admin.booklink }
        arguments: [null, Chitanka\LibBundle\Entity\BookLink, LibBundle:BookLinkAdmin]
    chitanka.admin.book_author:
        class: Chitanka\LibBundle\Admin\BookAuthorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_links, label: admin.bookauthor }
        arguments: [null, Chitanka\LibBundle\Entity\BookAuthor, LibBundle:BookAuthorAdmin]
    chitanka.admin.text_author:
        class: Chitanka\LibBundle\Admin\TextAuthorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_links, label: admin.textauthor }
        arguments: [null, Chitanka\LibBundle\Entity\TextAuthor, LibBundle:TextAuthorAdmin]
    chitanka.admin.text_translator:
        class: Chitanka\LibBundle\Admin\TextTranslatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_links, label: admin.texttranslator }
        arguments: [null, Chitanka\LibBundle\Entity\TextTranslator, LibBundle:TextTranslatorAdmin]
    chitanka.admin.series_author:
        class: Chitanka\LibBundle\Admin\SeriesAuthorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_links, label: admin.seriesauthor }
        arguments: [null, Chitanka\LibBundle\Entity\SeriesAuthor, LibBundle:SeriesAuthorAdmin]

    chitanka.admin.work_entry:
        class: Chitanka\LibBundle\Admin\WorkEntryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_intern, label: admin.workentry }
        arguments: [null, Chitanka\LibBundle\Entity\WorkEntry, LibBundle:WorkEntryAdmin]
    chitanka.admin.user:
        class: Chitanka\LibBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: library_intern, label: admin.user }
        arguments: [null, Chitanka\LibBundle\Entity\User, LibBundle:UserAdmin]


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
# assetic:
#     debug:          %kernel.debug%
#     use_controller: false
#     # java: /usr/bin/java
#     filters:
#         cssrewrite: ~
#         # closure:
#         #     jar: %kernel.root_dir%/java/compiler.jar
#         # yui_css:
#         #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default:
                mappings:
                    #FOSUserBundle: ~
                    LibBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# jms_security_extra:
#     secure_controllers:  true
#     secure_all_services: false

sonata_admin:
    dashboard_groups:
        library_main: ~
        library_secondary: ~

    templates:
        edit: LibBundle:Admin:edit.html.twig
