chitanka:
    resource: "@LibBundle/Resources/config/routing.yml"

_internal:
    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
    prefix:   /_50m3th1ng_w1ck3d_c0m35_th15_way

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
