homepage:
    pattern:        /
    defaults:       { _controller: LibBundle:Main:index }
    requirements:   { _method: get }

catalog:
    pattern:        /catalog.{_format}
    defaults:       { _controller: LibBundle:Main:catalog }
    requirements:   { _method: get, _format: atom }


# # #   PERSONS   # # #

authors:
    pattern:        /authors.{_format}
    defaults:       { _controller: LibBundle:Author:index, _format: html }
    requirements:   { _method: get, _format: html|atom }

authors_alt:
    pattern:        /author
    defaults:       { _controller: LibBundle:Main:redirect, route: authors }
    requirements:   { _method: get }

authors_by_alpha_index:
    pattern:        /authors/{by}.{_format}
    defaults:       { _controller: LibBundle:Author:listByAlphaIndex, _format: html }
    requirements:   { _method: get, by: first-name|last-name, _format: html|atom }
authors_by_alpha:
    pattern:        /authors/{by}/{letter}.{_format}/{page}
    defaults:       { _controller: LibBundle:Author:listByAlpha, page: 1, _format: html }
    requirements:   { _method: get, by: first-name|last-name, page: \d+, _format: html|atom }

authors_by_country_index:
    pattern:        /authors/country/{by}.{_format}
    defaults:       { _controller: LibBundle:Author:listByCountryIndex, by: first-name, _format: html }
    requirements:   { _method: get, by: first-name|last-name, _format: html|atom }
authors_by_country:
    pattern:        /authors/country/{country}/{by}.{_format}/{page}
    defaults:       { _controller: LibBundle:Author:listByCountry, by: first-name, page: 1, _format: html }
    requirements:   { _method: get, by: first-name|last-name, page: \d+, _format: html|atom }

translators:
    pattern:        /translators.{_format}
    defaults:       { _controller: LibBundle:Translator:index, _format: html }
    requirements:   { _method: get, _format: html|atom }

translators_alt:
    pattern:        /translator
    defaults:       { _controller: LibBundle:Main:redirect, route: translators }
    requirements:   { _method: get }

translators_by_alpha_index:
    pattern:        /translators/{by}.{_format}
    defaults:       { _controller: LibBundle:Translator:listByAlphaIndex, _format: html }
    requirements:   { _method: get, by: first-name|last-name, _format: html|atom }
translators_by_alpha:
    pattern:        /translators/{by}/{letter}.{_format}/{page}
    defaults:       { _controller: LibBundle:Translator:listByAlpha, page: 1, _format: html }
    requirements:   { _method: get, by: first-name|last-name, page: \d+, _format: html|atom }

persons_search:
    pattern:        /persons/search.{_format}
    defaults:       { _controller: LibBundle:Search:persons, _format: html }
    requirements:   { _method: get, _format: html|xml }

person_show:
    pattern:        /person/{slug}.{_format}
    defaults:       { _controller: LibBundle:Person:show, _format: html }
    requirements:   { _method: get, _format: html|atom }

person_show_books:
    pattern:        /person/{slug}/books.{_format}
    defaults:       { _controller: LibBundle:Person:showBooks, _format: html }
    requirements:   { _method: get, _format: html|atom }

person_show_texts:
    pattern:        /person/{slug}/texts.{_format}
    defaults:       { _controller: LibBundle:Person:showTexts, _format: html }
    requirements:   { _method: get, _format: html|atom }

person_show_translations:
    pattern:        /person/{slug}/translations.{_format}
    defaults:       { _controller: LibBundle:Person:showTranslations, _format: html }
    requirements:   { _method: get, _format: html|atom }

person_suggest:
    pattern:        /person/{slug}/suggest
    defaults:       { _controller: LibBundle:Person:suggest }

# legacy url
author_show:
    pattern:        /author/{name}
    defaults:       { _controller: LibBundle:Person:showRedirect }
    requirements:   { _method: get }

# legacy url
translator_show:
    pattern:        /translator/{name}
    defaults:       { _controller: LibBundle:Person:showRedirect }
    requirements:   { _method: get }


# # #   SERIES   # # #

series:
    pattern:        /series.{_format}
    defaults:       { _controller: LibBundle:Series:index, _format: html }
    requirements:   { _method: get, _format: html|atom }

series_alt:
    pattern:        /serie
    defaults:       { _controller: LibBundle:Main:redirect, route: series }
    requirements:   { _method: get }

series_search:
    pattern:        /series/search.{_format}
    defaults:       { _controller: LibBundle:Search:series, _format: html }
    requirements:   { _method: get, _format: html|xml }

series_by_alpha:
    pattern:        /series/alpha/{letter}.{_format}/{page}
    defaults:       { _controller: LibBundle:Series:listByAlpha, page: 1, _format: html }
    requirements:   { _method: get, page: \d+, _format: html|atom }

series_show:
    pattern:        /serie/{slug}.{_format}
    defaults:       { _controller: LibBundle:Series:show, _format: html }
    requirements:   { _method: get, _format: html|atom }


# # #   BOOKS   # # #

books:
    pattern:        /books.{_format}
    defaults:       { _controller: LibBundle:Book:index, _format: html }
    requirements:   { _method: get, _format: html|atom }

books_alt:
    pattern:        /book
    defaults:       { _controller: LibBundle:Main:redirect, route: books }
    requirements:   { _method: get }

books_search:
    pattern:        /books/search.{_format}
    defaults:       { _controller: LibBundle:Search:books, _format: html }
    requirements:   { _method: get, _format: html|xml }

books_by_alpha:
    pattern:        /books/alpha/{letter}.{_format}/{page}
    defaults:       { _controller: LibBundle:Book:listByAlpha, page: 1, _format: html }
    requirements:   { _method: get, page: \d+, _format: html|atom }

books_by_category:
    pattern:        /books/category/{slug}.{_format}/{page}
    defaults:       { _controller: LibBundle:Book:listByCategory, page: 1, _format: html }
    requirements:   { _method: get, page: \d+, _format: html|atom }

books_by_alpha_index:
    pattern:        /books/alpha.{_format}
    defaults:       { _controller: LibBundle:Book:listByAlphaIndex, _format: html }
    requirements:   { _method: get, _format: html|atom }

books_by_category_index:
    pattern:        /books/category.{_format}
    defaults:       { _controller: LibBundle:Book:listByCategoryIndex, _format: html }
    requirements:   { _method: get, _format: html|atom }

book_random:
    pattern:        /book/random
    defaults:       { _controller: LibBundle:Book:random }
    requirements:   { _method: get }

book_show:
    pattern:        /book/{id}.{_format}
    defaults:       { _controller: LibBundle:Book:show, _format: html }
    requirements:   { _method: get, _format: html|sfb|sfb\.zip|fb2|fb2\.zip|txt|txt\.zip|epub|djvu|clue|atom }

book_comments:
    pattern:        /book/{id}/comments.{_format}
    defaults:       { _controller: LibBundle:Book:comments, _format: html }

# book_suggest_info:
#     pattern:        /book/{id}/suggest/{object}
#     defaults:       { _controller: LibBundle:Book:suggest }


# # #   BOOK SEQUENCES   # # #

sequences:
    pattern:        /sequences.{_format}
    defaults:       { _controller: LibBundle:Sequence:index, _format: html }
    requirements:   { _method: get, _format: html|atom }

sequences_alt:
    pattern:        /sequence
    defaults:       { _controller: LibBundle:Main:redirect, route: sequences }
    requirements:   { _method: get }

sequences_search:
    pattern:        /sequences/search.{_format}
    defaults:       { _controller: LibBundle:Search:sequences, _format: html }
    requirements:   { _method: get, _format: html|xml }

sequences_by_alpha:
    pattern:        /sequences/alpha/{letter}.{_format}/{page}
    defaults:       { _controller: LibBundle:Sequence:listByAlpha, page: 1, _format: html }
    requirements:   { _method: get, page: \d+, _format: html|atom }

sequence_show:
    pattern:        /sequence/{slug}.{_format}
    defaults:       { _controller: LibBundle:Sequence:show, _format: html }
    requirements:   { _method: get, _format: html|atom }


# # #   TEXTS   # # #

texts_comments:
    pattern:        /texts/comments.{_format}/{page}
    defaults:       { _controller: LibBundle:TextComment:index, page: 1, _format: html }
    requirements:   { _method: get, page: \d+, _format: html|rss }

texts:
    pattern:        /texts.{_format}
    defaults:       { _controller: LibBundle:Text:index, _format: html }
    requirements:   { _method: get, _format: html|atom }

texts_alt:
    pattern:        /text
    defaults:       { _controller: LibBundle:Main:redirect, route: texts }
    requirements:   { _method: get }

texts_search:
    pattern:        /texts/search.{_format}
    defaults:       { _controller: LibBundle:Search:texts, _format: html }
    requirements:   { _method: get, _format: html|xml }

texts_by_alpha:
    pattern:        /texts/alpha/{letter}.{_format}/{page}
    defaults:       { _controller: LibBundle:Text:listByAlpha, page: 1, _format: html }
    requirements:   { _method: get, page: \d+, _format: html|atom }

texts_by_type:
    pattern:        /texts/type/{type}.{_format}/{page}
    defaults:       { _controller: LibBundle:Text:listByType, page: 1, _format: html }
    requirements:   { _method: get, page: \d+, _format: html|atom }

texts_by_label:
    pattern:        /texts/label/{slug}.{_format}/{page}
    defaults:       { _controller: LibBundle:Text:listByLabel, page: 1, _format: html }
    requirements:   { _method: get, page: \d+, _format: html|atom }

texts_by_alpha_index:
    pattern:        /texts/alpha.{_format}
    defaults:       { _controller: LibBundle:Text:listByAlphaIndex, _format: html }
    requirements:   { _method: get, _format: html|atom }

texts_by_type_index:
    pattern:        /texts/type.{_format}
    defaults:       { _controller: LibBundle:Text:listByTypeIndex, _format: html }
    requirements:   { _method: get, _format: html|atom }

texts_by_label_index:
    pattern:        /texts/label.{_format}
    defaults:       { _controller: LibBundle:Text:listByLabelIndex, _format: html }
    requirements:   { _method: get, _format: html|atom }

text_label_new:
    pattern:        /text/{id}/label/new
    defaults:       { _controller: LibBundle:Text:newLabel }
text_label_delete:
    pattern:        /text/{id}/label/{labelId}
    defaults:       { _controller: LibBundle:Text:deleteLabel }
    requirements:   { _method: delete }

text_random:
    pattern:        /text/random
    defaults:       { _controller: LibBundle:Text:random }
    requirements:   { _method: get }

text_comments:
    pattern:        /text/{id}/comments.{_format}
    defaults:       { _controller: LibBundle:TextComment:listForText, _format: html }

text_ratings:
    pattern:        /text/{id}/ratings
    defaults:       { _controller: LibBundle:Text:ratings }

text_rating:
    pattern:        /text/{id}/rating
    defaults:       { _controller: LibBundle:Text:rating }

text_similar:
    pattern:        /text/{id}/similar
    defaults:       { _controller: LibBundle:Text:similar }
    requirements:   { _method: get }

text_suggest_info:
    pattern:        /text/{id}/suggest/{object}
    defaults:       { _controller: LibBundle:Text:suggest }

text_read:
    pattern:        /text/{id}/read
    defaults:       { _controller: LibBundle:Text:markRead }
    requirements:   { _method: post, id: \d+ }

text_bookmark:
    pattern:        /text/{id}/mark
    defaults:       { _controller: LibBundle:Text:addBookmark }
    requirements:   { _method: post, id: \d+ }

text_show:
    pattern:        /text/{id}.{_format}
    defaults:       { _controller: LibBundle:Text:show, slug: test, _format: html }
    requirements:   { _method: get, _format: html|sfb|fb2|sfb\.zip|fb2\.zip|txt|txt\.zip|epub|clue|atom }

text_show_part:
    pattern:        /text/{id}/{part}
    defaults:       { _controller: LibBundle:Text:showPart, part: 1 }
    requirements:   { part: \d+ }

text_show_multi:
    pattern:        /text-multi/{id}.{_format}
    defaults:       { _controller: LibBundle:Text:showMulti, _format: html }
    requirements:   { _format: html|sfb\.zip|fb2\.zip|txt\.zip|epub }



about:
    pattern:   /about
    defaults: { _controller: LibBundle:Wiki:index, page: about }
rules:
    pattern:   /rules
    defaults: { _controller: LibBundle:Wiki:index, page: rules }
blacklist:
    pattern:   /blacklist
    defaults: { _controller: LibBundle:Wiki:index, page: blacklist }
links:
    pattern:   /links
    defaults: { _controller: LibBundle:Wiki:index, page: links }

search:
    pattern:   /search
    defaults: { _controller: LibBundle:Search:index }

sandbox:
    pattern:   /sandbox
    defaults: { _controller: LibBundle:Sandbox:index }

# sitemap:
#     pattern:   /sitemap
#     defaults: { _controller: LibBundle:Sitemap:index }

feedback:
    pattern:   /feedback
    defaults: { _controller: LibBundle:Feedback:index }

statistics:
    pattern:   /statistics
    defaults: { _controller: LibBundle:Statistics:index }

# opensearchdesc:
#     pattern:   /osd/{object}
#     defaults: { _controller: LibBundle:Opensearchdesc:index }


torrents:
    pattern:   /torrents
    defaults: { _controller: LibBundle:Torrent:index }

wanted:
    pattern:   /wanted
    defaults: { _controller: LibBundle:Wanted:index }


new:
    pattern:   /new
    defaults: { _controller: LibBundle:History:index }

new_books:
    pattern:   /new/books.{_format}
    defaults: { _controller: LibBundle:History:listBooks, _format: html }
    requirements:   { _method: get, _format: html|rss|atom }

new_books_by_month:
    pattern:   /new/books/{year}/{month}.{_format}/{page}
    defaults: { _controller: LibBundle:History:listBooksByMonth, page: 1, _format: html }
    requirements:
        _method: get
        year: \d+
        month: \d+
        page: \d+
        _format: html|atom

new_texts:
    pattern:   /new/texts.{_format}
    defaults: { _controller: LibBundle:History:listTexts, _format: html }
    requirements:   { _method: get, _format: html|rss|atom }

new_texts_by_month:
    pattern:   /new/texts/{year}/{month}.{_format}/{page}
    defaults: { _controller: LibBundle:History:listTextsByMonth, page: 1, _format: html }
    requirements:
        _method: get
        year: \d+
        month: \d+
        page: \d+
        _format: html|atom


user_email:
    pattern:   /user/{username}/email
    defaults: { _controller: LibBundle:User:email }
    options:
        segment_separators: [/]
# settings
user_edit:
    pattern:   /user/{username}/edit
    defaults: { _controller: LibBundle:User:edit }
    options:
        segment_separators: [/]
user_show:
    pattern:   /user/{username}
    defaults: { _controller: LibBundle:User:show }
    requirements: { _method: get }
    options:
        segment_separators: [/]
# old edituserpage
user_page_edit:
    pattern:   /user/{username}/page
    defaults: { _controller: LibBundle:User:page }
    options:
        segment_separators: [/]

user_comments:
    pattern:   /user/{username}/comments/{page}
    defaults: { _controller: LibBundle:User:comments, page: 1 }
    requirements: { _method: get, page: \d+ }
    options:
        segment_separators: [/]

user_ratings:
    pattern:   /user/{username}/ratings
    defaults: { _controller: LibBundle:User:ratings }
    requirements: { _method: get }
    options:
        segment_separators: [/]

user_contribs:
    pattern:   /user/{username}/contribs/{page}
    defaults: { _controller: LibBundle:User:contribs, page: 1 }
    requirements: { _method: get, page: \d+ }
    options:
        segment_separators: [/]

user_read_list:
    pattern:   /user/{username}/read/{page}
    defaults: { _controller: LibBundle:User:readList, page: 1 }
    requirements: { _method: get, page: \d+ }
    options:
        segment_separators: [/]

user_bookmarks:
    pattern:   /user/{username}/bookmarks/{page}
    defaults: { _controller: LibBundle:User:bookmarks, page: 1 }
    requirements: { _method: get, page: \d+ }
    options:
        segment_separators: [/]

user_special_texts:
    pattern:   /user-special-texts
    defaults: { _controller: LibBundle:User:specialTexts }


register:
    pattern:   /register
    defaults: { _controller: LibBundle:Security:register }
login:
    pattern:   /login
    defaults: { _controller: LibBundle:Security:login }
login_check:
    pattern:   /login_check
# logout:
#     pattern:   /logout
logout:
    pattern:   /signout
    defaults: { _controller: LibBundle:Security:logout }

request_password:
    pattern:   /request-password
    defaults: { _controller: LibBundle:Security:requestPassword }
request_username:
    pattern:   /request-username
    defaults: { _controller: LibBundle:Security:requestUsername }


workroom_entry_new:
    pattern:   /workroom/entry
    defaults: { _controller: LibBundle:Workroom:new }
    requirements: { _method: get }
workroom_entry_create:
    pattern:   /workroom/entry
    defaults: { _controller: LibBundle:Workroom:create }
    requirements: { _method: post }
workroom_entry_edit:
    pattern:   /workroom/entry/{id}
    defaults: { _controller: LibBundle:Workroom:edit }
    requirements: { _method: get }
workroom_entry_update:
    pattern:   /workroom/entry/{id}
    defaults: { _controller: LibBundle:Workroom:update }
    requirements: { _method: put }
workroom_entry_delete:
    pattern:   /workroom/entry/{id}
    defaults: { _controller: LibBundle:Workroom:delete }
    requirements: { _method: delete }

workroom_contrib:
    pattern:   /workroom/contributors
    defaults: { _controller: LibBundle:Workroom:listContributors }
    requirements: { _method: get }

workroom_contrib_delete:
    pattern:   /workroom/contrib/{id}
    defaults: { _controller: LibBundle:Workroom:deleteContrib }
    requirements: { _method: delete }

workroom:
    pattern:   /workroom/{status}/{page}
    defaults: { _controller: LibBundle:Workroom:index, status: all, page: 1 }
    requirements: { page: \d+ }

workroom_rss:
    pattern:   /workroom.rss
    defaults: { _controller: LibBundle:Workroom:rss }
    requirements: { _method: get }


featured_books:
    pattern:   /featured-books.{_format}
    defaults: { _controller: LibBundle:FeaturedBook:index, _format: html }
    requirements: { _format: html|rss }

foreign_books:
    pattern:   /foreign-books.{_format}
    defaults: { _controller: LibBundle:ForeignBook:index, _format: html }
    requirements: { _format: html|rss }

reviews:
    pattern:   /reviews
    defaults: { _controller: LibBundle:Feed:reviews }

# fos_user_security:
    # resource: @FOSUserBundle/Resources/config/routing/security.xml

# default:
#     pattern:   /{action}
#     defaults: { _controller: LibBundle:Main:default }
